### ISSUE TITLE
获取文件失败

### ISSUE THREAD

**Issue by changfeng1050** [leonHua/LFilePicker#1]
在onActivityResult中，条用data.getStringArrayExtra(Constant.RESULT_INFO) 为空
Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                     at tonda.tdledwizard.ui.UpdateFragment.onActivityResult(UpdateFragment.kt:209)
                                                                     at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:175)
                                                                     at android.app.Activity.dispatchActivityResult(Activity.java:6192)
                                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
                                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617) 
                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5258) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by leonHua** [comment]
感觉你是在Fragement中调取start()方法，如果是的话，要在Fragment中重写onActivityResult方法来获取数据
