### ISSUE TITLE
 A TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by xiaowei127** [leonHua/LFilePicker#19]
java.lang.RuntimeException: Unable to start activity ComponentInfo{a21theone.tbm/com.leon.lfilepickerlibrary.ui.LFilePickerActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747)
                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:187)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5879)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
                                                                Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                                                                   at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:555)
                                                                   at android.app.Activity.onApplyThemeResource(Activity.java:3767)
                                                                   at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
                                                                   at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
                                                                   at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:90)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2624)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747) 
                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                   at android.os.Looper.loop(Looper.java:194) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5879) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)

**Comment by leonHua** [comment]
你的开发和项目环境是？项目的版本，主题是什么？光看这个错误看不出来，可以看看demo中的工程环境和你的哪里不一样
