### ISSUE TITLE
一直点击上一级到顶部目录再点崩溃

### ISSUE THREAD

**Issue by MrPsw** [leonHua/LFilePicker#39]

**Comment by xvbo** [comment]
我使用1.8 并没有出现此问题

**Comment by MrPsw** [comment]
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:882)
        at java.util.TimSort.mergeAt(TimSort.java:499)
        at java.util.TimSort.mergeCollapse(TimSort.java:424)
        at java.util.TimSort.sort(TimSort.java:210)
        at java.util.Arrays.sort(Arrays.java:1998)
        at java.util.Collections.sort(Collections.java:1900)
        at com.leon.lfilepickerlibrary.utils.FileUtils.getFileListByDirPath(FileUtils.java:29)
        at com.leon.lfilepickerlibrary.utils.FileUtils.getFileList(FileUtils.java:72)
        at com.leon.lfilepickerlibrary.adapter.PathAdapter.onBindViewHolder(PathAdapter.java:79)
        at com.leon.lfilepickerlibrary.adapter.PathAdapter.onBindViewHolder(PathAdapter.java:25)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:17938)
        at android.view.ViewGroup.layout(ViewGroup.java:5812)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
        at android.view.View.layout(View.java:17938)
        at android.view.ViewGroup.layout(ViewGroup.java:5812)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
        at android.view.View.layout(View.java:17938)
        at android.view.ViewGroup.layout(ViewGroup.java:5812)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17938)
        at android.view.ViewGroup.layout(ViewGroup.java:5812)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
        at android.view.View.layout(View.java:17938)
        at android.view.ViewGroup.layout(ViewGroup.java:5812)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17938)
        at android.view.ViewGroup.layout(ViewGroup.java:5812)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
        at android.view.View.layout(View.java:17938)
        at android.view.ViewGroup.layout(ViewGroup.java:5812)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
    	at android.view.Choreographer.doCallbac

**Comment by xvbo** [comment]
你的运行环境是什么， 或许你可以尝试一下 把源码下下来以model的方式倒入，然后修改FileUtils 里的 getFileListByDirPath 方法

**Comment by MrPsw** [comment]
嗯，我在尝试修改，这个错误好像是由于jdk1.7的原因，1.6那个方法可以

**Comment by MrPsw** [comment]
解决：
  if (f1.isDirectory() == f2.isDirectory()) {
            return f1.getName().compareToIgnoreCase(f2.getName());
        }
        return f1.isDirectory() ? -1 : 1;
